sites:
  - id: jcanet
    name: 日本合唱指揮者協会
    url: https://jcanet.or.jp/index.html
    max_articles: 5

  - id: panamusica
    name: パナムジカ
    url: https://panamusica.co.jp/ja/info/
    max_articles: 5

settings:
  max_history_items: 500
  article_age_days: 30
