sites:
  - id: jcanet
    name: 日本合唱連盟
    url: https://jcanet.or.jp/index.html
    max_articles: 3

  - id: panamusica
    name: パナムジカ
    url: https://panamusica.co.jp/ja/info/
    max_articles: 3

  - id: choralnet-news
    name: ChoralNet News
    url: https://choralnet.org/acda-news
    max_articles: 3

  - id: choralnet-blog
    name: ChoralNet Blog
    url: https://choralnet.org/blog
    max_articles: 3

  - id: ifcm-news
    name: IFCM News
    url: https://www.ifcm.net/news
    max_articles: 3

settings:
  max_history_items: 500
  article_age_days: 3
