steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/choral-rss-bot/choral-web-scraper:${SHORT_SHA}",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/choral-rss-bot/choral-web-scraper:latest",
        "-f",
        "deploy/Dockerfile.web_scraper",
        ".",
      ]

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/choral-rss-bot/choral-web-scraper",
      ]

  # Update the Cloud Run Job
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "jobs"
      - "update"
      - "choral-web-scraper"
      - "--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/choral-rss-bot/choral-web-scraper:${SHORT_SHA}"
      - "--region=${_REGION}"

substitutions:
  _REGION: asia-northeast1

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/choral-rss-bot/choral-web-scraper"
